### ISSUE TITLE
Ensure cache is unlocked no matter what

### ISSUE THREAD

**Issue by tadeuzagallo** [onionskin/onionskin#1]
If something happens during cache generation and neither `save` or `set` are called the cache is never unlocked.
The solution might to create a new method on promises that is called when the chain is finished.

**Comment by tadeuzagallo** [comment]
@txgruppi What do you think?.
Thanks to @spion for the tip.

**Comment by txgruppi** [comment]
I just have one question.
What if the user call `.get` on a existing key?
The `.unlock` is in a `.catch` and it will only run if there is any error.

**Comment by tadeuzagallo** [comment]
`.get` just reads, it doesn't lock the cache
