### ISSUE TITLE
Using keys is bad for performance on large redis databases

### ISSUE THREAD

**Issue by rwky** [onionskin/onionskin#8]
When deleting using redis the driver runs the keys command which has performance implications see here http://redis.io/commands/keys

**Comment by tadeuzagallo** [comment]
On memcached I am already using namespaces: https://code.google.com/p/memcached/wiki/NewProgrammingTricks#Namespacing

On redis I still need to migrate, but it would require another script running from time to time to clear stale data, I was avoiding that at beginning.

**Comment by tadeuzagallo** [comment]
Related to #4.
Need to implement `purge` before.
