### ISSUE TITLE
Partitioned cache?

### ISSUE THREAD

**Issue by dmitry-saritasa** [onionskin/onionskin#9]
Hi,

PHP Stash has ability to define multiple servers, like this one

// Multiple Servers
$driver = new Stash\Driver\Redis();

$servers = array();
$servers[] = array('127.0.0.1');
$servers[] = array('10.10.10.20');
$servers[] = array('10.10.10.19', '6379');
$servers[] = array('10.10.10.19', '6380');

$driver->setOptions(array('servers' => $servers));

is this feature implemented inside onionskin? Or it's a single-server connection only?

**Comment by tadeuzagallo** [comment]
Not every driver has this feature, but Redis and Mecached do.
As it is exemplified here: [http://onionskin.io/api/#onionskin-drivers-memcached](http://onionskin.io/api/#onionskin-drivers-memcached)
The pamaters are passed to [node-memcached](https://github.com/3rd-Eden/node-memcached) and [node-redis](https://github.com/mranney/node_redis/), so onionskin does not deal with it.
If you have any doubts about syntax you can check their documentation, I don't really know about every option they offer, but the basic examples you can find at the api section on onionskin's site.

**Comment by dmitry-saritasa** [comment]
thanks!
